[package]
name = "aranya-client-capi"
description = "C API for the aranya-client library"
version = "2.0.0"                # choose same as related crates or set your own
authors = ["SpiderOak, Inc."]
edition = "2021"
license = "AGPL-3.0-only"
repository = "https://github.com/aranya-project/aranya"
rust-version = "1.85"

[lib]
crate-type = ["rlib", "cdylib"]
doctest = false

[features]
default = []

# Preview features
preview = ["aranya-client/preview"]
# Aranya Fast Channels
afc = ["aranya-client/afc"]

# Experimental features
experimental = ["aranya-client/experimental"]
# Aranya QUIC channels
aqc = ["aranya-client/aqc"]

# change to repo instead of crates.io
[dependencies]
aranya-client = { version = "3.0.0", git = "https://github.com/matcala/aranya.git", branch = "cosmos-gate",  features = ["preview", "afc", "aqc", "experimental"] }
aranya-daemon-api = { version = "3.0.0", git = "https://github.com/matcala/aranya.git", branch = "cosmos-gate", features = ["preview", "afc", "aqc", "experimental"] }
aranya-util = { version = "3.0.0", git = "https://github.com/matcala/aranya.git", branch = "cosmos-gate" }
aranya-capi-core = { version = "0.5.0" }
aranya-crypto = { version = "0.10.0", features = ["alloc", "fs-keystore", "clone-aead", "std", "tls"] }
buggy = { version = "0.1.0" }

anyhow = { version = "1.0.86" }
bytes = { version = "1.0" }
postcard = { version = "1", default-features = false, features = ["use-std", "heapless", "experimental-derive"] }
thiserror = { version = "2.0" }
tokio = { version = "1.44" }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }


[build-dependencies]
aranya-capi-codegen = { version = "0.4.0" }
anyhow = { version = "1.0.86" }
quote = "1"
syn = "2"

[package.metadata.cargo-all-features]
always_include_features = ["experimental", "preview"]
