# The name of the daemon used for logging and debugging
# purposes.
name = "cFS-aranya-daemon"

runtime_dir = "/run/aranya/run"
state_dir = "/run/aranya/state"
cache_dir = "/run/aranya/cache"
logs_dir = "/run/aranya/log"
config_dir = "/run/aranya/config"


# runtime_dir = "/var/run/aranya/run"
# state_dir = "/var/run/aranya/state"
# cache_dir = "/var/run/aranya/cache"
# logs_dir = "/var/run/aranya/logs"
# config_dir = "/var/run/aranya/config"

[afc]
enable = true
shm_path = "/shm_member"
max_chans = 100

[aqc]
enable = true

[sync.quic]
enable = true
# Aranya sync server listen address
addr = "0.0.0.0:9999"
