# The name of the daemon used for logging and debugging
# purposes.
name = "cFS-aranya-daemon"

name = "member"
runtime_dir = "/run/aranya/run"
state_dir = "/run/aranya/state"
cache_dir = "/run/aranya/cache"
logs_dir = "/run/aranya/logs"
config_dir = "/run/aranya/config"

[afc]
enable = true
shm_path = "/shm_member"
max_chans = 100

[aqc]
enable = true

[sync.quic]
enable = true
# Aranya sync server listen address
addr = "0.0.0.0:9999"
